### ISSUE TITLE
Brexit crash Rack when tring to delete it

### ISSUE THREAD

**Issue by nay-seven** [leopard86/LOGinstruments#1]
Hello,
Thanks for your plug-ins
Here on Mac Yosemite, when i push button and try to delete brexit, rack crash and i need to force to quit and delete autosave.vcv to open it again

**Comment by djhyperspace** [comment]
on Mac Sierra. same here. Brexit crashed rack. first crash I've ever had with rack

**Comment by LOGUNIVPM** [comment]
This is the intended behavior :) . "Brexit crashes the system". The module is meant to generate a segmentation fault and crash the whole application. 
Thanks for taking the time to report.

**Comment by djhyperspace** [comment]
SILLY BUT I LIKE IT...
