### ISSUE TITLE
version 1.0

### ISSUE THREAD

**Issue by gilbertohasnofb** [leopard86/LOGinstruments#12]
Your plugin is not compatible any longer with the current version of VCV Rack. Are you planning on updating it and releasing a new version?

**Comment by LOGUNIVPM** [comment]
Yes, unfortunately I'm lacking the time to update, but I'm planning on a 1.0 release and a rework of the GUI. Do you have specific modules you'd like to use? I have compiled the 1.0 version of Speck for my own use. I may be able to share that privately.

**Comment by gilbertohasnofb** [comment]
I think I mainly use Speck and Velvet. But there is absolutely no rush whatsoever, it's totally understand that you are busy. As for compiling and sharing privately these modules, don't worry about it, I am happy to wait for a possible release. I have just been sending messages to authors of  libraries that I find interesting and which have not been updated yet. Cheers!

**Comment by LOGUNIVPM** [comment]
Dear @gilbertohasnofb, I've struggled to find some spare time, but finally the 1.0 plugins are available on the store (and obviously here as source code).

**Comment by gilbertohasnofb** [comment]
thank you so much!
