### ISSUE TITLE
v2: References to custom fonts stored across frames

### ISSUE THREAD

**Issue by cschol** [leopard86/LOGinstruments#17]
Your plugin stores references to custom fonts across frames. This leads to crashes in the VST when reloading a project.

For example (but there might be others):
```
SpeckDisplay() {               
   font = APP->window->loadFont(asset::plugin(pluginInstance, "res/DejaVuSansMono.ttf"));
}
```

Please see the following link on how to resolve this issue and re-submit to the Library:
https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames

**Comment by LOGUNIVPM** [comment]
Thank you,
I have fixed this, and pushed my changes (new manifest 2.0.3)
I would test it on a DAW but I'm stuck with Ardour and Rack Studio on Linux crashing even without my modules.
Can you tell me how is it going now?

**Comment by cschol** [comment]
Your changes fix the issues. Thank you. You can submit the SHA to the library.
