### ISSUE TITLE
Binaries for Windows & Mac

### ISSUE THREAD

**Issue by PatchworkBoy** [leopard86/LOGinstruments#2]
Precompiled binaries for windows / mac are here: https://github.com/PatchworkBoy/LOGinstruments/releases/tag/v1.0

Feel free to download and re-release on here.

**Comment by LOGUNIVPM** [comment]
Thanks but I suggest sticking to my compiled binaries (for all 3 platforms) here: https://github.com/leopard86/LOGinstruments/releases
This will avoid confusion with zip archives going around on the web.
If there are issues my binaries please add a ticket here. If you forked to make changes please state clearly what were the changes.
Please note that the folder name should be LOGinstruments and not Leonardo.
Thank you, best regards

**Comment by PatchworkBoy** [comment]
(Your releases weren't there at the time or I wouldn't have bothered, hence forking and compiling for myself)
