### ISSUE TITLE
make error in arch linux 

### ISSUE THREAD

**Issue by Malifick** [leopard86/LOGinstruments#3]
make
g++ -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -Wsuggest-override -std=c++11 -c -o build/src/Britix.cpp.o src/Britix.cpp
src/Britix.cpp:64:7: warning: ‘virtual void Britix::step()’ can be marked override [-Wsuggest-override]
  void step();
       ^~~~
src/Britix.cpp:66:7: warning: ‘virtual void Britix::reset()’ can be marked override [-Wsuggest-override]
  void reset() {
       ^~~~~
src/Britix.cpp: In constructor ‘BritixWidget::BritixWidget()’:
src/Britix.cpp:216:11: error: ‘createValueLight’ was not declared in this scope
  addChild(createValueLight<TinyLight<GreenValueLight>>(Vec(81, 167), &module->lights1[0]));
           ^~~~~~~~~~~~~~~~
src/Britix.cpp:216:38: error: ‘GreenValueLight’ was not declared in this scope
  addChild(createValueLight<TinyLight<GreenValueLight>>(Vec(81, 167), &module->lights1[0]));
                                      ^~~~~~~~~~~~~~~
src/Britix.cpp:216:38: error: template argument 1 is invalid
src/Britix.cpp:217:38: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::TinyLight’
  addChild(createValueLight<TinyLight<GreenValueLight>>(Vec(111, 167), &module->lights1[1]));
                                      ^~~~~~~~~~~~~~~
src/Britix.cpp:217:38: note:   expected a type, got ‘GreenValueLight’
src/Britix.cpp:218:38: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::TinyLight’
  addChild(createValueLight<TinyLight<GreenValueLight>>(Vec(141, 167), &module->lights1[2]));
                                      ^~~~~~~~~~~~~~~
src/Britix.cpp:218:38: note:   expected a type, got ‘GreenValueLight’
src/Britix.cpp:241:38: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::TinyLight’
  addChild(createValueLight<TinyLight<GreenValueLight>>(Vec(81, 167+BOTTOM_VDIST), &module->lights2[0]));
                                      ^~~~~~~~~~~~~~~
src/Britix.cpp:241:38: note:   expected a type, got ‘GreenValueLight’
src/Britix.cpp:242:38: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::TinyLight’
  addChild(createValueLight<TinyLight<GreenValueLight>>(Vec(111, 167+BOTTOM_VDIST), &module->lights2[1]));
                                      ^~~~~~~~~~~~~~~
src/Britix.cpp:242:38: note:   expected a type, got ‘GreenValueLight’
src/Britix.cpp:243:38: error: type/value mismatch at argument 1 in template parameter list for ‘template<class BASE> struct rack::TinyLight’
  addChild(createValueLight<TinyLight<GreenValueLight>>(Vec(141, 167+BOTTOM_VDIST), &module->lights2[2]));
                                      ^~~~~~~~~~~~~~~
src/Britix.cpp:243:38: note:   expected a type, got ‘GreenValueLight’
make: *** [../../compile.mk:54: build/src/Britix.cpp.o] Error 1

**Comment by LOGUNIVPM** [comment]
The problem is with your VCV sources. You need to compile my 0.4.0 branch against VCV 0.4.0 sources or my keep-last branch against latest VCV sources (but I cannot confirm if something has changed in the last few days).

**Comment by Malifick** [comment]
I compiled the very latest vcv source code from github yesterday to try to get as many plugins as I can to work
