### ISSUE TITLE
Compile fails in Mint64

### ISSUE THREAD

**Issue by asbaklm** [leopard86/LOGinstruments#4]
^
In file included from ../../include/rack.hpp:7:0,
                 from src/LOGinstruments.hpp:1,
                 from src/LessMess.cpp:4:
../../include/engine.hpp:54:2: note: declared here
  Module() DEPRECATED {}
  ^
src/Speck.cpp: In member function ‘void SpeckDisplay::Stats::calculate(float*)’:
src/Speck.cpp:248:12: error: ‘gSampleRate’ was not declared in this scope
    peakx = gSampleRate/2.0 * ((float)(peakx) / (float)(FFT_POINTS_NYQ));
            ^
src/Speck.cpp: In member function ‘void SpeckDisplay::drawGrid(NVGcontext*, float, float, bool, float)’:
src/Speck.cpp:374:15: error: ‘gSampleRate’ was not declared in this scope
   float nyq = gSampleRate / 2.0;
               ^
../../compile.mk:53: recipe for target 'build/src/Speck.cpp.o' failed
make: *** [build/src/Speck.cpp.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by LOGUNIVPM** [comment]
Hi, I believe you have been cloning my repository while I was re-organizing its branches. At the moment I'm keeping a branch for compatibility with VCV 0.4.0 and the master branch with updates following the latest version of VCV from git.
If you need to compile against VCV 0.4.0 sources checkout the tag v0_4_0 with 
git checkout tags/v0_4_0
BTW: I will publish an updated version of the 0.4.0 binaries today.
If you need to compile against the latest version of VCV from git you can try with the current sources, but I'm not finished updating. I need some spare minutes to make it work...

**Comment by asbaklm** [comment]
Much appreciated thank you very much, I'll try the latest version. (I'm on a fairly recent version of rack, just before the change to RtAudio).
