### ISSUE TITLE
Question on Matrix

### ISSUE THREAD

**Issue by metaphorz** [leopard86/LOGinstruments#6]
I am now exploring your Matrix modular and read the README file, but it is not working as I expect.
If you put a RED PIN in the top left position, shouldn't the output of OUT1 be INA+INA (which should be equal to 1.0). I have INA, INB, and INC set equal to 0.5 in the Voltmeter and then I leave the last volt meter reading to be OUT1.

I am on a Mac and just now compiled your modules.
[LOGMatrixTest.vcv.zip](https://github.com/leopard86/LOGinstruments/files/1507956/LOGMatrixTest.vcv.zip)

**Comment by LOGUNIVPM** [comment]
Hi,
you got it correct, but there is a scaling factor at the end that is the inverse of the number of inputs, i.e. 
out1[i] = out1[i] / NUM_INPUTS_2
I put this to avoid too large values. Of course, if you feel that this behavior is not desired you can remove that line in the code (both for top and bottom matrices) or I can do that if this is not required by other users as well.

**Comment by metaphorz** [comment]
Thanks - I now follow the logic. I suggest though that you add the above to your README file when explaining the operation.

**Comment by LOGUNIVPM** [comment]
Thanks
