### ISSUE TITLE
Velvet: weird output

### ISSUE THREAD

**Issue by phdsg** [leopard86/LOGinstruments#7]
OS: win7-64
Rack: dev
Plugin: dev

i had a couple of crashes the other day and it always involved an instance of your velvet noise gen.
these were somewhat evolved patches, so it's hard to find the actual cause.
so i went ahead and did a clean setup with only velvet and the scope.
and there's definitely something not right.
in it's initial state, velvet is silent on both outputs. in fact "w" is always silent.
there's just a fine range (above zero) on the knob that actually makes velvet shoot some pulses of around -32V (-10V in the 2nd mode).
turning the knob further just produces some constant value up to -1.25V in 100% position.

**Comment by LOGUNIVPM** [comment]
Thanks for the notice. Indeed in the last commit there was a leftover that made the random generation not viable. I am committing a new version and reuploading the compiled binaries.

**Comment by phdsg** [comment]
nice, thx.
is it on purpose that the white noise is offset by +5V?
